config/routes.rb
Rails.application.routes.draw do
  root to: 'players#index'

  devise_for :players, :controllers => { :registrations => "registrations" }
  resources :matches, only: [:new, :create, :show]
  resources :players, only: [:show, :index] do
    resources :matches, only: [:index]
  end

  resources :challenges, only: [:create]
end

app/models/match.rb
class Match < ActiveRecord::Base
  belongs_to :player1, class_name: 'Player'
  belongs_to :player2, class_name: 'Player'

  validates_presence_of :player1_id, :player2_id, :score_player1, :score_player2, :match_date
  validates_numericality_of :score_player1, :score_player2, { only_integer: true, greater_than_or_equal_to: 0, less_than_or_equal_to: 10 }
  validate :scores_cannot_be_the_same

  def scores_cannot_be_the_same
    if score_player1 == score_player2
      errors.add(:score_player1, "can't be the same as score for player 2")
    end
  end

  def self.matches_between_players(player1, player2)
    if self.where("player1_id IN (?) AND player2_id IN (?)", [player1, player2], [player1, player2]).count > 0
      self.where("player1_id IN (?) AND player2_id IN (?)", [player1, player2], [player1, player2])
    else
      []
    end
  end

  def self.recent_matches(player)
    if self.where("player1_id = ? OR player2_id = ?", player, player).count > 0
      self.where("player1_id = ? OR player2_id = ?", player, player).order(match_date: :desc).limit(5)
    else
      []
    end
  end
end

app/models/player.rb
class Player < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :host_matches, class_name: 'Match', foreign_key: 'player1_id'
  has_many :guest_matches, class_name: 'Match', foreign_key: 'player2_id'

  mount_uploader :avatar, AvatarUploader

  validates_presence_of :first_name, :last_name

  def full_name
    "#{first_name} #{last_name}"
  end

  def update_winning_player_stats(goals_scored, goals_lost)
    self.add_match_played
    self.add_win
    self.update_current_streak
    if self.current_streak > self.longest_streak
      self.longest_streak += 1
    end
    self.update_total_goals_scored(goals_scored)
    self.update_total_goals_lost(goals_lost)
    self.update_points
    self.save
  end

  def update_losing_player_stats(goals_scored, goals_lost)
    self.add_match_played
    self.add_loss
    self.reset_current_streak
    self.update_total_goals_scored(goals_scored)
    self.update_total_goals_lost(goals_lost)
    self.save
  end

  def win_ratio
    if self.matches_played == 0
      0
    else
      (self.number_of_wins.to_f / self.matches_played) * 100
    end
  end

  def add_match_played
    self.matches_played += 1
  end

  def add_win
    self.number_of_wins += 1
  end

  def add_loss
    self.number_of_losses += 1
  end

  def update_current_streak
    self.current_streak += 1
  end

  def reset_current_streak
    self.current_streak = 0
  end

  def update_total_goals_scored(goals)
    self.total_goals_scored += goals
  end

  def update_total_goals_lost(goals)
    self.total_goals_lost += goals
  end

  def update_points
    self.points += 10
  end

  def average_goals
    (self.total_goals_scored.to_f / self.matches_played).round(1)
  end

  def find_player_position
    Player.order(points: :desc).index(self) + 1
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:first_name, :last_name, :email, :password, :password_confirmation, :avatar, :avatar_cache) }
    devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:first_name, :last_name, :email, :password, :password_confirmation, :current_password, :avatar, :avatar_cache) }
  end
end

app/controllers/challenges_controller.rb
class ChallengesController < ApplicationController
  before_action :authenticate_player!

  def create
    @recipient = Player.find(params[:player_id])
    @sender = current_player
    @message = params[:message]
    PlayerMailer.send_challenge(@sender, @recipient, @message).deliver_now
    flash[:notice] = "Challenge has been sent!"
    redirect_to @recipient
  end
end

app/controllers/matches_controller.rb
class MatchesController < ApplicationController
  before_action :authenticate_player!, only: [:new, :create]

  def new
    @match = Match.new
  end

  def create
    @match = Match.new(match_params)

    if @match.save
      player1 = Player.find(params[:match][:player1_id])
      player2 = Player.find(params[:match][:player2_id])
      score_player1 = params[:match][:score_player1].to_i
      score_player2 = params[:match][:score_player2].to_i
      handle_winner_and_loser(player1, player2, score_player1, score_player2)
      flash[:notice] = "Match successfully added!"
      redirect_to match_path(@match)
    else
      flash[:danger] = "Please check below error messages"
      render :new
    end
  end

  def show
    @match = Match.find(params[:id])
    @previous_matches = Match.matches_between_players(@match.player1, @match.player2)
  end

  def index
    @matches = Match.where('player1_id = ? OR player2_id = ?', params[:player_id], params[:player_id])
  end

  private

  def match_params
    params.require(:match).permit(:player1_id, :player2_id, :score_player1, :score_player2, :match_date)
  end

  def handle_winner_and_loser(player1, player2, score_player1, score_player2)
    if score_player1 > score_player2
      player1.update_winning_player_stats(score_player1, score_player2)
      player2.update_losing_player_stats(score_player2, score_player1)
    else
      player1.update_losing_player_stats(score_player1, score_player2)
      player2.update_winning_player_stats(score_player2, score_player1)
    end
  end
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  helper_method :sort_column, :sort_direction

  def show
    @player = Player.find(params[:id])
    @recent_matches = Match.recent_matches(@player)
  end

  def index
    @players = Player.order(sort_column + ' ' + sort_direction)
  end

  private

  def sort_column
    Player.column_names.include?(params[:sort]) ? params[:sort] : "points"
  end

  def sort_direction
    %w[asc desc].include?(params[:direction]) ? params[:direction] : "desc"
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  protected

  def after_sign_up_path_for(resource)
    root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def show_avatar(player)
    if player.avatar?
      image_tag player.avatar.url
    else
      image_tag "default.gif"
    end
  end

  def pretty_date(date)
    date.strftime("%d %b %Y")
  end

  def sortable(column, title = nil)
    title ||= column.split("_").join(" ").titleize
    css_class = (column == sort_column) ? "current #{sort_direction}" : nil
    direction = (column == sort_column && sort_direction == 'desc') ? 'asc' : 'desc'
    link_to title, { sort: column, direction: direction }, { class: css_class }
  end

  def options_for_players
    Player.where('id != ?', current_player.id).order(first_name: :asc).map { |p| [p.full_name, p.id] }
  end

  def display_trophy(player)
    if player.find_player_position == 1
      image_tag "Trophy-gold-icon.png", class: "trophy-img"
    elsif player.find_player_position == 2
      image_tag "Trophy-silver-icon.png", class: "trophy-img"
    elsif player.find_player_position == 3
      image_tag "Trophy-bronze-icon.png", class: "trophy-img"
    end
  end
end

app/views/layouts/application.html.haml
!!! 5
%html
  %head
    %title Foosball Tracker
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
    = stylesheet_link_tag 'http://fonts.googleapis.com/css?family=Pacifico'
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags

  %body
    %nav.navbar.navbar-inverse
      .container-fluid
        .navbar-header
          = link_to "Foosball Mania!", root_path, class: "navbar-brand"

        %ul.nav.navbar-nav.navbar-right
          - if player_signed_in?
            %li= link_to "Add new match", new_match_path
            %li= link_to "Sign Out", destroy_player_session_path, method: "delete"
          - else
            %li= link_to "Sign Up", new_player_registration_path
            %li= link_to "Sign In", new_player_session_path

    .container-fluid
      .row
        .col-sm-12
          = render 'shared/messages'

          = yield

app/views/matches/_match.html.haml
%tr
  %td.table-center
    = match.player1.full_name
  %td.table-center
    = link_to "#{match.score_player1} : #{match.score_player2}", match
  %td.table-center
    = match.player2.full_name

app/views/matches/index.html.haml
.col-sm-8.col-sm-offset-2
  %h2.text-center Matches played

  %table.table
    - @matches.each do |match|
      = render match

app/views/matches/new.html.haml
.well.col-sm-8.col-sm-offset-2
  %h2 Add a match

  %p
    = bootstrap_form_for @match do |f|
      %table.table
        %thead
          %tr
            %th
            %th Host
            %th Guest

        %tbody
          %tr
            %td.vert-align
              %strong Players
            %td.vert-align.table-center= current_player.full_name
            %td.vert-align= f.select :player2_id, options_for_players, hide_label: true
          %tr
            %td.vert-align
              %strong Score
            %td.vert-align= f.text_field :score_player1, hide_label: true
            %td.vert-align= f.text_field :score_player2, hide_label: true

      .text-center
        = f.date_select :match_date

        = f.hidden_field(:player1_id, value: current_player.id)
        = f.submit

app/views/matches/show.html.haml
.col-sm-6.col-sm-offset-3
  .panel.panel-success
    .panel-heading
      %h3.panel-title Match: #{pretty_date(@match.match_date)}

    .panel-body.text-center
      %tr
        %td.table-center
          = link_to @match.player1.full_name, @match.player1
        %td.table-center
          %strong= "#{@match.score_player1} : #{@match.score_player2}"
        %td.table-center
          = link_to @match.player2.full_name, @match.player2

  .panel.panel-success
    .panel-heading
      %h3.panel-title All matches between these players
    .panel-body
      %table.table
        - @previous_matches.each do |match|
          = render match

app/views/players/index.html.haml
<h2>Rankings</h2>

%table.table
  %thead
    %tr
      %th= sortable "first_name", "Full Name"
      %th= sortable "matches_played"
      %th= sortable "number_of_wins"
      %th= sortable "number_of_losses"
      %th= sortable "total_goals_scored"
      %th= sortable "total_goals_lost"
      %th= sortable "points"

  %tbody
  - @players.each do |player|
    %tr
      %td
        = link_to player.full_name, player
        = display_trophy(player)
      %td.table-center= link_to player.matches_played, player_matches_path(player)
      %td.table-center= player.number_of_wins
      %td.table-center= player.number_of_losses
      %td.table-center= player.total_goals_scored
      %td.table-center= player.total_goals_lost
      %td.table-center= player.points

app/views/players/show.html.haml
.text-center
  = show_avatar(@player)

%table.table
  %thead
    %tr
      %th{colspan: 2}
        .player-name
          = @player.full_name
          = display_trophy(@player)
    - if current_player && current_player == @player
      %tr
        %th{colspan: 2}= link_to "Edit player profile", edit_player_registration_path

  %tbody
    %tr
      %td Matches played
      %td= @player.matches_played
    %tr
      %td Number of wins
      %td= @player.number_of_wins
    %tr
      %td Number of losses
      %td= @player.number_of_losses
    %tr
      %td Win %
      %td= number_to_percentage(@player.win_ratio, precision: 1)
    %tr
      %td Goals scored
      %td= @player.total_goals_scored
    %tr
      %td Goals lost
      %td= @player.total_goals_lost
    %tr
      %td Average goals scored per game
      %td= @player.average_goals
    %tr
      %td Current winning streak
      %td= @player.current_streak
    %tr
      %td Longest winning streak
      %td= @player.longest_streak
    %tr
      %td Number of points
      %td= @player.points

.col-sm-5.col-sm-offset-1
  .panel.panel-success
    .panel-heading
      %h3.panel-title Recent matches
    .panel-body
      %table.table
        - @recent_matches.each do |match|
          = render '/matches/match', match: match

- if current_player && current_player != @player
  .col-sm-5
    .well
      %h4 Challenge this player for a match!
      = form_tag('/challenges') do
        = hidden_field_tag :player_id, @player.id
        .form-group
          = text_area_tag :message, nil, rows: 8, class: "form-control", placeholder: "Enter a personalized message with details, such as suggested date, etc."
        %br
        .text-center= submit_tag "Send challenge", class: "btn btn-default"

app/views/shared/_messages.html.haml
- flash.each do |key, msg|
  %div{class: "alert alert-dismissable alert-#{key.to_s == "notice" ? "success" : "danger"}"}
    %button{class: "close", type: "button", data: { dismiss: "alert" }} x
    = msg